export interface ExerciseGuide {
  id: string;
  name: string;
  muscleGroup: 'shoulders' | 'chest' | 'back' | 'arms' | 'legs' | 'core' | 'traps';
  subCategory: string;
  tips: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  gif: any;
  thumb: any;
  video: any;
}

export const MUSCLE_EXERCISES_DATA: Record<string, ExerciseGuide[]> = {
  chest: [
    {
      id: 'bench_press',
      name: 'Barbell Bench Press',
      muscleGroup: 'chest',
      subCategory: 'Overall Chest & Triceps',
      tips: 'Retract scapula, keep feet firmly planted, drive bar up evenly from lower chest.',
      primaryMuscles: ['Pectoralis Major'],
      secondaryMuscles: ['Triceps', 'Anterior Deltoids'],
      gif: require('../assets/exercises/gifs/bench_press.gif'),
      thumb: require('../assets/exercises/thumbs/bench_press.jpg'),
      video: require('../assets/exercises/videos/bench_press.mp4'),
    },
    {
      id: 'push_ups',
      name: 'Bodyweight Push-ups',
      muscleGroup: 'chest',
      subCategory: 'Compound Bodyweight',
      tips: 'Keep core tight in a straight plank line. Lower until chest nearly touches the floor.',
      primaryMuscles: ['Pectoralis Major', 'Core'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      gif: require('../assets/exercises/gifs/push_ups.gif'),
      thumb: require('../assets/exercises/thumbs/push_ups.jpg'),
      video: require('../assets/exercises/videos/push_ups.mp4'),
    },
    {
      id: 'cable_crossovers',
      name: 'Cable Fly Crossovers',
      muscleGroup: 'chest',
      subCategory: 'Inner & Lower Pec Isolation',
      tips: 'Slight bend in elbows, bring handles together in front of sternum and squeeze inner chest.',
      primaryMuscles: ['Pectoralis Major (Inner/Lower)'],
      secondaryMuscles: ['Anterior Deltoids'],
      gif: require('../assets/exercises/gifs/cable_crossovers.gif'),
      thumb: require('../assets/exercises/thumbs/cable_crossovers.jpg'),
      video: require('../assets/exercises/videos/cable_crossovers.mp4'),
    },
    {
      id: 'seated_cable_rows',
      name: 'Seated Cable Chest Press',
      muscleGroup: 'chest',
      subCategory: 'Chest & Back Balance',
      tips: 'Sit tall with chest forward. Press handles smoothly forward and squeeze at full extension.',
      primaryMuscles: ['Pectoralis Major'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      gif: require('../assets/exercises/gifs/seated_cable_rows.gif'),
      thumb: require('../assets/exercises/thumbs/seated_cable_rows.jpg'),
      video: require('../assets/exercises/videos/seated_cable_rows.mp4'),
    },
  ],

  back: [
    {
      id: 'pull_ups',
      name: 'Wide Grip Pull-ups',
      muscleGroup: 'back',
      subCategory: 'Lat Width & Upper Back',
      tips: 'Pull with your elbows, lift chest to the bar, squeeze lats hard at peak contraction.',
      primaryMuscles: ['Latissimus Dorsi', 'Rhomboids'],
      secondaryMuscles: ['Biceps', 'Rear Delts'],
      gif: require('../assets/exercises/gifs/pull_ups.gif'),
      thumb: require('../assets/exercises/thumbs/pull_ups.jpg'),
      video: require('../assets/exercises/videos/pull_ups.mp4'),
    },
    {
      id: 'lat_pulldowns',
      name: 'Cable Lat Pulldown',
      muscleGroup: 'back',
      subCategory: 'Lat Width',
      tips: 'Lean back slightly, pull bar down toward upper chest, drive elbows downward.',
      primaryMuscles: ['Latissimus Dorsi'],
      secondaryMuscles: ['Middle Traps', 'Biceps'],
      gif: require('../assets/exercises/gifs/lat_pulldowns.gif'),
      thumb: require('../assets/exercises/thumbs/lat_pulldowns.jpg'),
      video: require('../assets/exercises/videos/lat_pulldowns.mp4'),
    },
    {
      id: 'barbell_rows',
      name: 'Bent-Over Barbell Row',
      muscleGroup: 'back',
      subCategory: 'Back Density & Thickness',
      tips: 'Hinge 45 degrees at hips, keep spine neutral, pull bar to upper abdomen.',
      primaryMuscles: ['Rhomboids', 'Latissimus Dorsi'],
      secondaryMuscles: ['Erector Spinae', 'Biceps'],
      gif: require('../assets/exercises/gifs/barbell_rows.gif'),
      thumb: require('../assets/exercises/thumbs/barbell_rows.jpg'),
      video: require('../assets/exercises/videos/barbell_rows.mp4'),
    },
    {
      id: 'tbar_rows',
      name: 'T-Bar Row',
      muscleGroup: 'back',
      subCategory: 'Mid-Back Thickness',
      tips: 'Drive through heels, squeeze shoulder blades together at top of lift.',
      primaryMuscles: ['Middle Traps', 'Rhomboids'],
      secondaryMuscles: ['Lats', 'Biceps'],
      gif: require('../assets/exercises/gifs/tbar_rows.gif'),
      thumb: require('../assets/exercises/thumbs/tbar_rows.jpg'),
      video: require('../assets/exercises/videos/tbar_rows.mp4'),
    },
    {
      id: 'dumbbell_rows',
      name: 'Single-Arm Dumbbell Row',
      muscleGroup: 'back',
      subCategory: 'Unilateral Lat & Rhomboid',
      tips: 'Support knee on bench, pull dumbbell smoothly to hip without rotating torso.',
      primaryMuscles: ['Latissimus Dorsi', 'Rhomboids'],
      secondaryMuscles: ['Posterior Delts'],
      gif: require('../assets/exercises/gifs/dumbbell_rows.gif'),
      thumb: require('../assets/exercises/thumbs/dumbbell_rows.jpg'),
      video: require('../assets/exercises/videos/dumbbell_rows.mp4'),
    },
    {
      id: 'hyperextensions',
      name: 'Back Hyperextensions',
      muscleGroup: 'back',
      subCategory: 'Lower Back & Spinal Erectors',
      tips: 'Hinge at waist, raise torso until parallel with hips. Avoid hyperextending spine.',
      primaryMuscles: ['Erector Spinae', 'Glutes'],
      secondaryMuscles: ['Hamstrings'],
      gif: require('../assets/exercises/gifs/hyperextensions.gif'),
      thumb: require('../assets/exercises/thumbs/hyperextensions.jpg'),
      video: require('../assets/exercises/videos/hyperextensions.mp4'),
    },
    {
      id: 'romanian_deadlifts',
      name: 'Romanian Deadlifts (RDL)',
      muscleGroup: 'back',
      subCategory: 'Posterior Chain & Lower Back',
      tips: 'Push hips back with slight knee bend, feel deep stretch in hamstrings and glutes.',
      primaryMuscles: ['Hamstrings', 'Glutes', 'Lower Back'],
      secondaryMuscles: ['Forearms', 'Core'],
      gif: require('../assets/exercises/gifs/romanian_deadlifts.gif'),
      thumb: require('../assets/exercises/thumbs/romanian_deadlifts.jpg'),
      video: require('../assets/exercises/videos/romanian_deadlifts.mp4'),
    },
  ],

  shoulders: [
    {
      id: 'overhead_press',
      name: 'Barbell Military Press',
      muscleGroup: 'shoulders',
      subCategory: 'Compound Shoulder Mass',
      tips: 'Squeeze glutes and core, press bar overhead in straight path close to face.',
      primaryMuscles: ['Anterior & Lateral Deltoids'],
      secondaryMuscles: ['Triceps', 'Upper Chest'],
      gif: require('../assets/exercises/gifs/overhead_press.gif'),
      thumb: require('../assets/exercises/thumbs/overhead_press.jpg'),
      video: require('../assets/exercises/videos/overhead_press.mp4'),
    },
    {
      id: 'dumbbell_overhead_press',
      name: 'Dumbbell Shoulder Press',
      muscleGroup: 'shoulders',
      subCategory: 'Overhead Strength',
      tips: 'Press dumbbells up in a slight arc without letting them clank at the top.',
      primaryMuscles: ['Front & Side Deltoids'],
      secondaryMuscles: ['Triceps'],
      gif: require('../assets/exercises/gifs/dumbbell_overhead_press.gif'),
      thumb: require('../assets/exercises/thumbs/dumbbell_overhead_press.jpg'),
      video: require('../assets/exercises/videos/dumbbell_overhead_press.mp4'),
    },
    {
      id: 'seated_shoulder_press',
      name: 'Seated Dumbbell Press',
      muscleGroup: 'shoulders',
      subCategory: 'Strict Shoulder Isolation',
      tips: 'Keep back flat against pad. Lower weights until upper arms are 90 degrees.',
      primaryMuscles: ['Anterior Deltoids'],
      secondaryMuscles: ['Lateral Deltoids', 'Triceps'],
      gif: require('../assets/exercises/gifs/seated_shoulder_press.gif'),
      thumb: require('../assets/exercises/thumbs/seated_shoulder_press.jpg'),
      video: require('../assets/exercises/videos/seated_shoulder_press.mp4'),
    },
    {
      id: 'lateral_raises',
      name: 'Dumbbell Lateral Raises',
      muscleGroup: 'shoulders',
      subCategory: 'Side Delt Cap',
      tips: 'Lead with elbows, raise arms to shoulder level as if pouring a glass of water.',
      primaryMuscles: ['Lateral Deltoids (Side Head)'],
      secondaryMuscles: ['Traps'],
      gif: require('../assets/exercises/gifs/lateral_raises.gif'),
      thumb: require('../assets/exercises/thumbs/lateral_raises.jpg'),
      video: require('../assets/exercises/videos/lateral_raises.mp4'),
    },
    {
      id: 'cable_lateral_raises',
      name: 'Cable Lateral Raises',
      muscleGroup: 'shoulders',
      subCategory: 'Continuous Side Delt Tension',
      tips: 'Maintain constant cable tension, raise arm smoothly across body to shoulder height.',
      primaryMuscles: ['Lateral Deltoids'],
      secondaryMuscles: ['Traps'],
      gif: require('../assets/exercises/gifs/cable_lateral_raises.gif'),
      thumb: require('../assets/exercises/thumbs/cable_lateral_raises.jpg'),
      video: require('../assets/exercises/videos/cable_lateral_raises.mp4'),
    },
    {
      id: 'front_raises',
      name: 'Dumbbell Front Raises',
      muscleGroup: 'shoulders',
      subCategory: 'Front Delt Isolation',
      tips: 'Raise dumbbell in front to eye level under strict control without momentum.',
      primaryMuscles: ['Anterior Deltoids'],
      secondaryMuscles: ['Upper Chest'],
      gif: require('../assets/exercises/gifs/front_raises.gif'),
      thumb: require('../assets/exercises/thumbs/front_raises.jpg'),
      video: require('../assets/exercises/videos/front_raises.mp4'),
    },
    {
      id: 'reverse_flyes',
      name: 'Dumbbell Reverse Flyes',
      muscleGroup: 'shoulders',
      subCategory: 'Rear Delt Isolation',
      tips: 'Bend forward at waist, raise dumbbells out to sides squeezing posterior delts.',
      primaryMuscles: ['Rear Deltoids'],
      secondaryMuscles: ['Rhomboids'],
      gif: require('../assets/exercises/gifs/reverse_flyes.gif'),
      thumb: require('../assets/exercises/thumbs/reverse_flyes.jpg'),
      video: require('../assets/exercises/videos/reverse_flyes.mp4'),
    },
  ],

  arms: [
    {
      id: 'barbell_bicep_curls',
      name: 'Barbell Bicep Curls',
      muscleGroup: 'arms',
      subCategory: 'Bicep Mass',
      tips: 'Keep elbows locked at sides. Flex biceps hard at peak without swinging back.',
      primaryMuscles: ['Biceps Brachii'],
      secondaryMuscles: ['Brachialis', 'Forearms'],
      gif: require('../assets/exercises/gifs/barbell_bicep_curls.gif'),
      thumb: require('../assets/exercises/thumbs/barbell_bicep_curls.jpg'),
      video: require('../assets/exercises/videos/barbell_bicep_curls.mp4'),
    },
    {
      id: 'bicep_curls',
      name: 'Alternating Dumbbell Curls',
      muscleGroup: 'arms',
      subCategory: 'Bicep Peak & Supination',
      tips: 'Rotate wrist upward (supinate) as you curl dumbbell toward shoulder.',
      primaryMuscles: ['Biceps Brachii'],
      secondaryMuscles: ['Forearms'],
      gif: require('../assets/exercises/gifs/bicep_curls.gif'),
      thumb: require('../assets/exercises/thumbs/bicep_curls.jpg'),
      video: require('../assets/exercises/videos/bicep_curls.mp4'),
    },
    {
      id: 'tricep_dips',
      name: 'Tricep Bodyweight Dips',
      muscleGroup: 'arms',
      subCategory: 'Tricep Mass & Compound',
      tips: 'Keep torso upright to target triceps. Lower until upper arm is 90 degrees.',
      primaryMuscles: ['Triceps Brachii'],
      secondaryMuscles: ['Chest', 'Front Shoulders'],
      gif: require('../assets/exercises/gifs/tricep_dips.gif'),
      thumb: require('../assets/exercises/thumbs/tricep_dips.jpg'),
      video: require('../assets/exercises/videos/tricep_dips.mp4'),
    },
    {
      id: 'seated_cable_rows',
      name: 'Cable Tricep Pushdowns',
      muscleGroup: 'arms',
      subCategory: 'Tricep Cable Isolation',
      tips: 'Pin elbows to ribs, press bar down until arms are fully extended.',
      primaryMuscles: ['Triceps (Lateral & Medial Head)'],
      secondaryMuscles: ['Forearms'],
      gif: require('../assets/exercises/gifs/seated_cable_rows.gif'),
      thumb: require('../assets/exercises/thumbs/seated_cable_rows.jpg'),
      video: require('../assets/exercises/videos/seated_cable_rows.mp4'),
    },
  ],

  legs: [
    {
      id: 'squats',
      name: 'Barbell Back Squats',
      muscleGroup: 'legs',
      subCategory: 'Lower Body Compound Mass',
      tips: 'Break at hips and knees simultaneously. Drive up through mid-foot keeping chest high.',
      primaryMuscles: ['Quadriceps', 'Gluteus Maximus'],
      secondaryMuscles: ['Hamstrings', 'Calves', 'Core'],
      gif: require('../assets/exercises/gifs/squats.gif'),
      thumb: require('../assets/exercises/thumbs/squats.jpg'),
      video: require('../assets/exercises/videos/squats.mp4'),
    },
    {
      id: 'leg_press',
      name: 'Heavy Leg Press',
      muscleGroup: 'legs',
      subCategory: 'Quad & Glute Hypertrophy',
      tips: 'Place feet hip-width on sled. Lower platform under control without rounding lower back.',
      primaryMuscles: ['Quadriceps', 'Glutes'],
      secondaryMuscles: ['Hamstrings'],
      gif: require('../assets/exercises/gifs/leg_press.gif'),
      thumb: require('../assets/exercises/thumbs/leg_press.jpg'),
      video: require('../assets/exercises/videos/leg_press.mp4'),
    },
    {
      id: 'hip_thrust',
      name: 'Barbell Hip Thrust',
      muscleGroup: 'legs',
      subCategory: 'Glute Isolation & Power',
      tips: 'Rest upper back on bench, drive bar up through heels until hips are fully extended.',
      primaryMuscles: ['Gluteus Maximus'],
      secondaryMuscles: ['Hamstrings', 'Adductors'],
      gif: require('../assets/exercises/gifs/hip_thrust.gif'),
      thumb: require('../assets/exercises/thumbs/hip_thrust.jpg'),
      video: require('../assets/exercises/videos/hip_thrust.mp4'),
    },
    {
      id: 'walking_lunges',
      name: 'Walking Lunges',
      muscleGroup: 'legs',
      subCategory: 'Unilateral Leg Strength',
      tips: 'Take large strides forward, lower back knee toward floor, push up through front heel.',
      primaryMuscles: ['Quadriceps', 'Glutes'],
      secondaryMuscles: ['Hamstrings', 'Calves'],
      gif: require('../assets/exercises/gifs/walking_lunges.gif'),
      thumb: require('../assets/exercises/thumbs/walking_lunges.jpg'),
      video: require('../assets/exercises/videos/walking_lunges.mp4'),
    },
    {
      id: 'leg_extensions',
      name: 'Seated Leg Extensions',
      muscleGroup: 'legs',
      subCategory: 'Quad Peak Contraction',
      tips: 'Sit flush against seat. Extend legs fully and pause for 1 second at top squeeze.',
      primaryMuscles: ['Quadriceps (Rectus Femoris)'],
      secondaryMuscles: ['Patellar Tendon'],
      gif: require('../assets/exercises/gifs/leg_extensions.gif'),
      thumb: require('../assets/exercises/thumbs/leg_extensions.jpg'),
      video: require('../assets/exercises/videos/leg_extensions.mp4'),
    },
    {
      id: 'standing_calf_raises',
      name: 'Standing Calf Raises',
      muscleGroup: 'legs',
      subCategory: 'Gastrocnemius Calf Growth',
      tips: 'Drop heel deep for stretch, explode up onto toes and squeeze calves at top.',
      primaryMuscles: ['Gastrocnemius (Calves)'],
      secondaryMuscles: ['Soleus'],
      gif: require('../assets/exercises/gifs/standing_calf_raises.gif'),
      thumb: require('../assets/exercises/thumbs/standing_calf_raises.jpg'),
      video: require('../assets/exercises/videos/standing_calf_raises.mp4'),
    },
    {
      id: 'seated_calf_raises',
      name: 'Seated Calf Raises',
      muscleGroup: 'legs',
      subCategory: 'Soleus Muscle Isolation',
      tips: 'Keep knees bent 90 degrees to isolate lower calf soleus muscle.',
      primaryMuscles: ['Soleus'],
      secondaryMuscles: ['Gastrocnemius'],
      gif: require('../assets/exercises/gifs/seated_calf_raises.gif'),
      thumb: require('../assets/exercises/thumbs/seated_calf_raises.jpg'),
      video: require('../assets/exercises/videos/seated_calf_raises.mp4'),
    },
  ],

  traps: [
    {
      id: 'barbell_shrugs',
      name: 'Heavy Barbell Shrugs',
      muscleGroup: 'traps',
      subCategory: 'Upper Trapezius Growth',
      tips: 'Shrug shoulders straight up toward ears. Hold peak squeeze for 1-2 seconds.',
      primaryMuscles: ['Upper Trapezius'],
      secondaryMuscles: ['Levator Scapulae', 'Forearms'],
      gif: require('../assets/exercises/gifs/barbell_shrugs.gif'),
      thumb: require('../assets/exercises/thumbs/barbell_shrugs.jpg'),
      video: require('../assets/exercises/videos/barbell_shrugs.mp4'),
    },
  ],

  core: [
    {
      id: 'crunches',
      name: 'Bodyweight Ab Crunches',
      muscleGroup: 'core',
      subCategory: 'Upper Rectus Abdominis',
      tips: 'Flex ribs toward hips, contract abs hard at peak without pulling neck.',
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Obliques'],
      gif: require('../assets/exercises/gifs/crunches.gif'),
      thumb: require('../assets/exercises/thumbs/crunches.jpg'),
      video: require('../assets/exercises/videos/crunches.mp4'),
    },
  ],
};
